"""
DS Project - Study App v2 (75/25 balanced datasets)

Uses the 75% banking77 / 25% clinc150 study sets generated by the
EXPERIMENT SETS cell in notebooks/system_workflow_demo.ipynb.

Files live in:  outputs/user_study/study_v2/
  study_set_small.csv   — 16 queries  (12 b77, 4 clinc150)
  study_set_medium.csv  — 32 queries  (24 b77, 8 clinc150)
  study_set_large.csv   — 48 queries  (36 b77, 12 clinc150)

The active set is controlled by STUDY_SET (Streamlit secrets):
  small | medium | large    default: small

Dropbox folder: /ds_project_queries/study_v2/
"""

import streamlit as st
from pathlib import Path
import sys
import os

# Configure page
st.set_page_config(
    page_title="Customer Service Assistant",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# Add project root to path (MUST be done before any local imports)
project_root = str(Path(__file__).parent.absolute())
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Set working directory to project root
os.chdir(project_root)

# Point load_study_queries() at the v2 directory (75/25 sets)
os.environ['STUDY_SET_DIR'] = 'outputs/user_study/study_v2'
os.environ.setdefault('STUDY_SET', 'small')

# Import the simple banking assistant interface
try:
    from src.streamlit_app.simple_banking_assistant import main as banking_main
except ImportError as e:
    st.error(f"Failed to import banking assistant: {e}")
    st.error("Please check that all files are in the correct locations")
    st.stop()


def main():
    """Run the study app with the 75/25 balanced query sets."""
    banking_main()


if __name__ == "__main__":
    main()
